### ISSUE TITLE
Failed to instalat the firware of esp8266 and the tinyweb module

### ISSUE THREAD

**Issue by anjamago** [belyalov/tinyweb#14]
Make sure you are running the latest version of TinyWeb before reporting an issue.

**Device and/or platform:**
ESP8266

**Description of problem:**
hi try to install the firmware of esp8266 to use the module tinyweb because I need to have my esp with support to AJAX requests but at the time of importing it tells me that this module does not exist any ide with which you can access

**Expected:**

**Traceback (if applicable):**
```bash
import tintyweb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>                        
ImportError: no module named 'tintyweb' 
```

**Additional info:**

**Comment by belyalov** [comment]
I think the problem was just in typo: `tinTyweb` :)

It was resolved in a [neighborhood thread](https://github.com/micropython/micropython/issues/3714).
