### ISSUE TITLE
LmacRxblk:1 error

### ISSUE THREAD

**Issue by 2niuhe** [belyalov/tinyweb#22]
Make sure you are running the latest version of TinyWeb before reporting an issue.

**Device and/or platform:**
ESP8266
micropython latest version

**Description of problem:**
when my phone lost connection,then  reconnect to the AP,
LmacRxblk:1 erro occur.
**Expected:**

**Traceback (if applicable):**
```bash

```

**Additional info:**
I am new to python,maybe you don't close sock when CTRL+C interrupt.
maybe you can check this link
[https://forum.micropython.org/viewtopic.php?t=3602]

**Comment by belyalov** [comment]
Don't you mind to share your program?
It is currently unclear...

**Comment by 2niuhe** [comment]
I have solve the problem.It's caused by another mqtt package.
Thanks for your tinyweb project again.
