### ISSUE TITLE
Disable CodeFactor.io warning

### ISSUE THREAD

**Issue by metachris** [belyalov/tinyweb#37]
@belyalov could you disable this codefactor.io warning: https://github.com/belyalov/tinyweb/pull/36/checks?check_run_id=1503119325 (i hate seeing my PRs fail the pipeline for no reason)
 
Should work like this: https://support.codefactor.io/i18-ignoring-issues-and-patterns

**Comment by belyalov** [comment]
Thanks, ignored this one.
